<Database Name="" Class="QPContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SPBDEVSQL01\DEV;Initial Catalog=qa_demosite;User ID=publishing;Password=QuantumartHost.SQL;Connect Timeout=120;Application Name=QP8Backend" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="qp_database" Provider="System.Data.SqlClient" />
  <Table Name="STATUS_TYPE" Member="StatusTypes">
    <Type Name="StatusType">
      <Column Name="SITE_ID" Member="SiteId" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="STATUS_TYPE_ID" Member="Id" Type="System.Int32" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATUS_TYPE_NAME" Member="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WEIGHT" Member="Weight" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Member="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="CREATED" Member="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Member="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Member="LastModifiedBy" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_537_LIVE" Member="QPAbstractItems">
    <Type Name="QPAbstractItem">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Parent]" Member="Parent_ID" Storage="_Parent" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IsVisible]" Member="IsVisible" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IsPage]" Member="IsPage" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ZoneName]" Member="ZoneName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[AllowedUrlPatterns]" Member="AllowedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[DeniedUrlPatterns]" Member="DeniedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Discriminator]" Member="Discriminator_ID" Storage="_Discriminator" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[VersionOf]" Member="VersionOf_ID" Storage="_VersionOf" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Culture]" Member="Culture_ID" Storage="_Culture" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Keywords]" Member="Keywords" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[MetaDescription]" Member="MetaDescription" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[Tags]" Member="Tags" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[IsInSiteMap]" Member="IsInSiteMap" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IndexOrder]" Member="IndexOrder" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[ExtensionId]" Member="ExtensionId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[ContentId]" Member="ContentId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TitleFormat]" Member="TitleFormat_ID" Storage="_TitleFormat" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Parent_QPAbstractItem" Member="Parent" Storage="_Parent1" ThisKey="Parent_ID" OtherKey="Id" Type="QPAbstractItem" IsForeignKey="true" />
      <Association Name="Discriminator_QPAbstractItem" Member="Discriminator" Storage="_Discriminator1" ThisKey="Discriminator_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="VersionOf_QPAbstractItem" Member="VersionOf" Storage="_VersionOf1" ThisKey="VersionOf_ID" OtherKey="Id" Type="QPAbstractItem" IsForeignKey="true" />
      <Association Name="Culture_QPAbstractItem" Member="Culture" Storage="_Culture1" ThisKey="Culture_ID" OtherKey="Id" Type="QPCulture" IsForeignKey="true" />
      <Association Name="Parent_QPAbstractItem" Member="Children" ThisKey="Id" OtherKey="Parent_ID" Type="QPAbstractItem" />
      <Association Name="VersionOf_QPAbstractItem" Member="Versions" ThisKey="Id" OtherKey="VersionOf_ID" Type="QPAbstractItem" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_538_LIVE" Member="QPDiscriminators">
    <Type Name="QPDiscriminator">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[PreferredContentId]" Member="PreferredContentId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TypeName]" Member="TypeName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[CategoryName]" Member="CategoryName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[IconUrl]" Member="IconUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IsPage]" Member="IsPage" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[AllowedZones]" Member="AllowedZones" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[FilterPartByUrl]" Member="FilterPartByUrl" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Source_QPItemDefinitionConstraint" Member="AllowedItemDefinitions" ThisKey="Id" OtherKey="Source_ID" Type="QPItemDefinitionConstraint" />
      <Association Name="QPDiscriminator_88" Member="ItemDefinitionItemDefinitionArticles" ThisKey="Id" OtherKey="QPDiscriminator_ID" Type="ItemDefinitionItemDefinitionArticle" />
      <Association Name="Discriminator_QPAbstractItem" Member="Items" ThisKey="Id" OtherKey="Discriminator_ID" Type="QPAbstractItem" />
      <Association Name="Target_QPItemDefinitionConstraint" Member="AllowDefinition" ThisKey="Id" OtherKey="Target_ID" Type="QPItemDefinitionConstraint" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_540_LIVE" Member="QPCultures">
    <Type Name="QPCulture">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Icon]" Member="Icon" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Culture_QPAbstractItem" Member="AbstractItems" ThisKey="Id" OtherKey="Culture_ID" Type="QPAbstractItem" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10609_LIVE" Member="QPItemDefinitionConstraints">
    <Type Name="QPItemDefinitionConstraint">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Target]" Member="Target_ID" Storage="_Target" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Source]" Member="Source_ID" Storage="_Source" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Target_QPItemDefinitionConstraint" Member="Target" Storage="_Target1" ThisKey="Target_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="Source_QPItemDefinitionConstraint" Member="Source" Storage="_Source1" ThisKey="Source_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LINK_88" Member="ItemDefinitionItemDefinitionArticles">
    <Type Name="ItemDefinitionItemDefinitionArticle">
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="QPDiscriminator_ID" Storage="_ITEM_ID" />
      <Column Name="LINKED_ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="QPDiscriminator_ID2" Storage="_LINKED_ITEM_ID" />
      <Association Name="QPDiscriminator_88" Member="QPDiscriminator" Storage="_QPDiscriminator1" ThisKey="QPDiscriminator_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="QPDiscriminator_88" Member="QPDiscriminator2" Storage="_QPDiscriminator12" ThisKey="QPDiscriminator_ID2" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.qp_abs_time" Method="AbsTime" IsComposable="true">
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" DbType="Decimal" />
  </Function>
</Database>