version: '3.4'
services:
  demositeapi:
    build:
      context: . # выполняем в контексте папки исходников
      dockerfile: ./QA.Demosite.API/Dockerfile
      network: host
      args:
        PROJECT_NAME: QA.Demosite.API
    container_name: wpdemo.api
    # dns: 127.0.0.53
    ports:
      - 5000:80
    environment:
      QpSettings__ConfigurationServiceUrl: http://qp-conf-service.dev.qsupport.ru
      QpSettings__ConfigurationServiceToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJRUC5Db25maWd1cmF0aW9uU2VydmljZS5Jc3N1ZXIiLCJleHAiOjE2MDg1ODM4NjIsImF1ZCI6IlFQLkNvbmZpZ3VyYXRpb25TZXJ2aWNlLkF1ZGllbmNlIn0.CB5JOeeEHibhN1_WB7cTT4pv27MZUYn_xmV2QW4F9p0
      QpSettings__CustomerCode: demo_site_pg_react

  razzleapp:
    build:
      context: ./QA.DemoSite.ReactFrontend
      dockerfile: Dockerfile
      network: host
    container_name: wpdemo.front
    ports:
      - 3000:3000
    environment:
      API_BASE_URL: http://demositeapi/api
    