// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace QA.DemoSite.Postgre.DAL
{
    public partial class AbTestClientRedirect: IQPArticle
    {
        public AbTestClientRedirect()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalVersionNumber;
		public virtual String VersionNumber 
		{ 
			get { return _internalVersionNumber; }
			set { _internalVersionNumber = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
		private String _internalRedirectUrl;
		public virtual String RedirectUrl 
		{ 
			get { return _internalRedirectUrl; }
			set { _internalRedirectUrl = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>			
		public virtual AbTestClientRedirectContainer Container { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Container_ID { get; set; }
	}
}
	
