// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace QA.DemoSite.Postgre.DAL
{
    public partial class BlogPost2BlogTagForTags: IQPLink
    {
		public BlogPost BlogPostItem { get; set; }		
		public BlogTag BlogTagLinkedItem { get; set; }

		public int BlogPostItemId { get; set; }	
		public int BlogTagLinkedItemId { get; set; }

		public int LinkId
		{
			get { return 140; }
		}

		public int Id 
		{ 
			get { return BlogPostItemId; } 
			set { BlogPostItemId = value; } 
		}
        public int LinkedItemId 
		{ 
			get { return BlogTagLinkedItemId; }
			set { BlogTagLinkedItemId = value; }
		}
		public IQPArticle Item { get { return BlogPostItem; } }		
		public IQPArticle LinkedItem { get { return BlogTagLinkedItem; } }
	}

}
	
	
	
