// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace QA.DemoSite.Postgre.DAL
{
    public partial class BlogPost: IQPArticle
    {
        public BlogPost()
        {
		    Tags = new HashSet<BlogPost2BlogTagForTags>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalTitle;
		public virtual String Title 
		{ 
			get { return _internalTitle; }
			set { _internalTitle = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
		private String _internalBrief;
		public virtual String Brief 
		{ 
			get { return _internalBrief; }
			set { _internalBrief = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual DateTime? PostDate { get; set; }
		private String _internalText;
		public virtual String Text 
		{ 
			get { return _internalText; }
			set { _internalText = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual String Image { get; set; }
		private String _internalYoutubeVideoCode;
		public virtual String YoutubeVideoCode 
		{ 
			get { return _internalYoutubeVideoCode; }
			set { _internalYoutubeVideoCode = PostgreQpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>			
		public virtual BlogCategory Category { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Category_ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<BlogPost2BlogTagForTags> Tags { get; set; }
	}
}
	
