<Database Name="" Class="QpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SPBDEVSQL01\DEV;Initial Catalog=qa_demosite;User ID=publishing;Password=QuantumartHost.SQL;Connect Timeout=120;Application Name=QP8Backend" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="qp_database" Provider="System.Data.SqlClient" />
  <Table Name="STATUS_TYPE" Member="StatusTypes">
    <Type Name="StatusType">
      <Column Name="SITE_ID" Member="SiteId" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="STATUS_TYPE_ID" Member="Id" Type="System.Int32" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATUS_TYPE_NAME" Member="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WEIGHT" Member="Weight" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Member="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="CREATED" Member="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Member="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Member="LastModifiedBy" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_537_LIVE" Member="QPAbstractItems">
    <Type Name="QPAbstractItem">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Parent]" Member="Parent_ID" Storage="_Parent" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IsVisible]" Member="IsVisible" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IsPage]" Member="IsPage" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ZoneName]" Member="ZoneName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[AllowedUrlPatterns]" Member="AllowedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[DeniedUrlPatterns]" Member="DeniedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Discriminator]" Member="Discriminator_ID" Storage="_Discriminator" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[VersionOf]" Member="VersionOf_ID" Storage="_VersionOf" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Culture]" Member="Culture_ID" Storage="_Culture" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Keywords]" Member="Keywords" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[MetaDescription]" Member="MetaDescription" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[Tags]" Member="Tags" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[IsInSiteMap]" Member="IsInSiteMap" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[IndexOrder]" Member="IndexOrder" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[ExtensionId]" Member="ExtensionId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[ContentId]" Member="ContentId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TitleFormat]" Member="TitleFormat_ID" Storage="_TitleFormat" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Parent_QPAbstractItem" Member="Parent" Storage="_Parent1" ThisKey="Parent_ID" OtherKey="Id" Type="QPAbstractItem" IsForeignKey="true" />
      <Association Name="Discriminator_QPAbstractItem" Member="Discriminator" Storage="_Discriminator1" ThisKey="Discriminator_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="VersionOf_QPAbstractItem" Member="VersionOf" Storage="_VersionOf1" ThisKey="VersionOf_ID" OtherKey="Id" Type="QPAbstractItem" IsForeignKey="true" />
      <Association Name="Culture_QPAbstractItem" Member="Culture" Storage="_Culture1" ThisKey="Culture_ID" OtherKey="Id" Type="QPCulture" IsForeignKey="true" />
      <Association Name="Parent_QPAbstractItem" Member="Children" ThisKey="Id" OtherKey="Parent_ID" Type="QPAbstractItem" />
      <Association Name="VersionOf_QPAbstractItem" Member="Versions" ThisKey="Id" OtherKey="VersionOf_ID" Type="QPAbstractItem" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_538_LIVE" Member="QPDiscriminators">
    <Type Name="QPDiscriminator">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[PreferredContentId]" Member="PreferredContentId" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TypeName]" Member="TypeName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[CategoryName]" Member="CategoryName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[IconUrl]" Member="IconUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IsPage]" Member="IsPage" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[AllowedZones]" Member="AllowedZones" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[FilterPartByUrl]" Member="FilterPartByUrl" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Source_QPItemDefinitionConstraint" Member="AllowedItemDefinitions" ThisKey="Id" OtherKey="Source_ID" Type="QPItemDefinitionConstraint" />
      <Association Name="QPDiscriminator_88" Member="ItemDefinitionItemDefinitionArticles" ThisKey="Id" OtherKey="QPDiscriminator_ID" Type="ItemDefinitionItemDefinitionArticle" />
      <Association Name="Discriminator_QPAbstractItem" Member="Items" ThisKey="Id" OtherKey="Discriminator_ID" Type="QPAbstractItem" />
      <Association Name="Target_QPItemDefinitionConstraint" Member="AllowDefinition" ThisKey="Id" OtherKey="Target_ID" Type="QPItemDefinitionConstraint" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_540_LIVE" Member="QPCultures">
    <Type Name="QPCulture">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Name]" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Icon]" Member="Icon" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Culture_QPAbstractItem" Member="AbstractItems" ThisKey="Id" OtherKey="Culture_ID" Type="QPAbstractItem" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10609_LIVE" Member="QPItemDefinitionConstraints">
    <Type Name="QPItemDefinitionConstraint">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Target]" Member="Target_ID" Storage="_Target" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Source]" Member="Source_ID" Storage="_Source" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Target_QPItemDefinitionConstraint" Member="Target" Storage="_Target1" ThisKey="Target_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="Source_QPItemDefinitionConstraint" Member="Source" Storage="_Source1" ThisKey="Source_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10663_LIVE" Member="AbTests">
    <Type Name="AbTest">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Enabled]" Member="Enabled" Type="System.Boolean" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Percentage]" Member="Percentage" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[StartDate]" Member="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[EndDate]" Member="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Comment]" Member="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ParentTest_AbTestBaseContainer" Member="ABTestContainers" ThisKey="Id" OtherKey="ParentTest_ID" Type="AbTestBaseContainer" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10664_LIVE" Member="AbTestBaseContainers">
    <Type Name="AbTestBaseContainer">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[ParentTest]" Member="ParentTest_ID" Storage="_ParentTest" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[AllowedUrlPatterns]" Member="AllowedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[DeniedUrlPatterns]" Member="DeniedUrlPatterns" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Domain]" Member="Domain" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Precondition]" Member="Precondition" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Arguments]" Member="Arguments" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Type]" Member="Type" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Association Name="ParentTest_AbTestBaseContainer" Member="ParentTest" Storage="_ParentTest1" ThisKey="ParentTest_ID" OtherKey="Id" Type="AbTest" IsForeignKey="true" />
      <Association Name="BaseContainer_AbTestScriptContainer" Member="ScriptContainers" ThisKey="Id" OtherKey="BaseContainer_ID" Type="AbTestScriptContainer" />
      <Association Name="BaseContainer_AbTestClientRedirectContainer" Member="ClientRedirectContainers" ThisKey="Id" OtherKey="BaseContainer_ID" Type="AbTestClientRedirectContainer" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10665_LIVE" Member="AbTestScripts">
    <Type Name="AbTestScript">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Container]" Member="Container_ID" Storage="_Container" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Description]" Member="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[VersionNumber]" Member="VersionNumber" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[ScriptText]" Member="ScriptText" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Container_AbTestScript" Member="Container" Storage="_Container1" ThisKey="Container_ID" OtherKey="Id" Type="AbTestScriptContainer" IsForeignKey="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10666_LIVE" Member="AbTestScriptContainers">
    <Type Name="AbTestScriptContainer">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BaseContainer]" Member="BaseContainer_ID" Storage="_BaseContainer" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="BaseContainer_AbTestScriptContainer" Member="BaseContainer" Storage="_BaseContainer1" ThisKey="BaseContainer_ID" OtherKey="Id" Type="AbTestBaseContainer" IsForeignKey="true" />
      <Association Name="Container_AbTestScript" Member="ScriptsInContainer" ThisKey="Id" OtherKey="Container_ID" Type="AbTestScript" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10667_LIVE" Member="AbTestClientRedirectContainers">
    <Type Name="AbTestClientRedirectContainer">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BaseContainer]" Member="BaseContainer_ID" Storage="_BaseContainer" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="BaseContainer_AbTestClientRedirectContainer" Member="BaseContainer" Storage="_BaseContainer1" ThisKey="BaseContainer_ID" OtherKey="Id" Type="AbTestBaseContainer" IsForeignKey="true" />
      <Association Name="Container_AbTestClientRedirect" Member="ClientRedirectsInContainer" ThisKey="Id" OtherKey="Container_ID" Type="AbTestClientRedirect" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_10668_LIVE" Member="AbTestClientRedirects">
    <Type Name="AbTestClientRedirect">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Container]" Member="Container_ID" Storage="_Container" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[VersionNumber]" Member="VersionNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[RedirectUrl]" Member="RedirectUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Container_AbTestClientRedirect" Member="Container" Storage="_Container1" ThisKey="Container_ID" OtherKey="Id" Type="AbTestClientRedirectContainer" IsForeignKey="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_30745_LIVE" Member="BlogPosts">
    <Type Name="BlogPost">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Brief]" Member="Brief" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[PostDate]" Member="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Category]" Member="Category_ID" Storage="_Category" Type="System.Int32" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[Text]" Member="Text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Image]" Member="Image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[YoutubeVideoCode]" Member="YoutubeVideoCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Category_BlogPost" Member="Category" Storage="_Category1" ThisKey="Category_ID" OtherKey="Id" Type="BlogCategory" IsForeignKey="true" />
      <Association Name="BlogPost_140" Member="BlogPostyBlogTegiArticles" ThisKey="Id" OtherKey="BlogPost_ID" Type="BlogPostyBlogTegiArticle" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_30746_LIVE" Member="BlogCategories">
    <Type Name="BlogCategory">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SortOrder]" Member="SortOrder" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Association Name="Category_BlogPost" Member="PostsInCategory" ThisKey="Id" OtherKey="Category_ID" Type="BlogPost" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_30747_LIVE" Member="BlogTags">
    <Type Name="BlogTag">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Title]" Member="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTENT_30749_LIVE" Member="FaqItems">
    <Type Name="FaqItem">
      <Column Name="CONTENT_ITEM_ID" Type="System.Int32" Member="Id" DbType="Decimal(18,0) IDENTITY NOT NULL" IsPrimaryKey="true" CanBeNull="false" IsDbGenerated="true" />
      <Column Name="STATUS_TYPE_ID" Type="System.Int32" Member="StatusTypeId" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.Boolean" Member="Visible" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ARCHIVE" Type="System.Boolean" Member="Archive" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CREATED" Type="System.DateTime" Member="Created" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED" Type="System.DateTime" Member="Modified" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MODIFIED_BY" Type="System.Int32" Member="LastModifiedBy" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Question]" Member="Question" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Answer]" Member="Answer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[SortOrder]" Member="SortOrder" Type="System.Int32" DbType="Decimal(38,0)" CanBeNull="true" />
      <Association Name="StatusType_ContentItem" Member="StatusType" ThisKey="StatusTypeId" OtherKey="Id" Type="StatusType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LINK_88" Member="ItemDefinitionItemDefinitionArticles">
    <Type Name="ItemDefinitionItemDefinitionArticle">
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="QPDiscriminator_ID" Storage="_ITEM_ID" />
      <Column Name="LINKED_ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="QPDiscriminator_ID2" Storage="_LINKED_ITEM_ID" />
      <Association Name="QPDiscriminator_88" Member="QPDiscriminator" Storage="_QPDiscriminator1" ThisKey="QPDiscriminator_ID" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
      <Association Name="QPDiscriminator_88" Member="QPDiscriminator2" Storage="_QPDiscriminator12" ThisKey="QPDiscriminator_ID2" OtherKey="Id" Type="QPDiscriminator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LINK_140" Member="BlogPostyBlogTegiArticles">
    <Type Name="BlogPostyBlogTegiArticle">
      <Column Name="ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="BlogPost_ID" Storage="_ITEM_ID" />
      <Column Name="LINKED_ITEM_ID" Type="System.Int32" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" IsPrimaryKey="true" Member="BlogTag_ID" Storage="_LINKED_ITEM_ID" />
      <Association Name="BlogPost_140" Member="BlogPost" Storage="_BlogPost1" ThisKey="BlogPost_ID" OtherKey="Id" Type="BlogPost" IsForeignKey="true" />
      <Association Name="BlogTag_140" Member="BlogTag" Storage="_BlogTag1" ThisKey="BlogTag_ID" OtherKey="Id" Type="BlogTag" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.qp_abs_time" Method="AbsTime" IsComposable="true">
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" DbType="Decimal" />
  </Function>
</Database>