// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace QA.DemoSite.Mssql.DAL
{
    public partial class AbTest: IQPArticle
    {
        public AbTest()
        {
		    ABTestContainers = new HashSet<AbTestBaseContainer>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalTitle;
		public virtual String Title 
		{ 
			get { return _internalTitle; }
			set { _internalTitle = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual Boolean? Enabled { get; set; }
		private String _internalPercentage;
		public virtual String Percentage 
		{ 
			get { return _internalPercentage; }
			set { _internalPercentage = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual DateTime? StartDate { get; set; }
        public virtual DateTime? EndDate { get; set; }
		private String _internalComment;
		public virtual String Comment 
		{ 
			get { return _internalComment; }
			set { _internalComment = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<AbTestBaseContainer> ABTestContainers { get; set; }
	}
}
	
