// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace QA.DemoSite.Mssql.DAL
{
    public partial class QPAbstractItem: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<QPAbstractItem, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<QPAbstractItem,  IQPFormService, string>>
        {
			{ "Title", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "Name", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Name != null ? ctx.ReplacePlaceholders(self.Name) : null) },
			{ "Parent_ID", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Parent_ID != null ? self.Parent_ID.ToString() : null) },
			{ "IsVisible", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.IsVisible != null ? self.IsVisible.Value ? "1" : "0" : null) },
			{ "IsPage", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.IsPage != null ? self.IsPage.Value ? "1" : "0" : null) },
			{ "ZoneName", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.ZoneName != null ? ctx.ReplacePlaceholders(self.ZoneName) : null) },
			{ "AllowedUrlPatterns", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.AllowedUrlPatterns != null ? ctx.ReplacePlaceholders(self.AllowedUrlPatterns) : null) },
			{ "DeniedUrlPatterns", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.DeniedUrlPatterns != null ? ctx.ReplacePlaceholders(self.DeniedUrlPatterns) : null) },
			{ "Description", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Description != null ? ctx.ReplacePlaceholders(self.Description) : null) },
			{ "Discriminator_ID", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Discriminator_ID != null ? self.Discriminator_ID.ToString() : null) },
			{ "VersionOf_ID", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.VersionOf_ID != null ? self.VersionOf_ID.ToString() : null) },
			{ "Culture_ID", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Culture_ID != null ? self.Culture_ID.ToString() : null) },
			{ "Keywords", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Keywords != null ? ctx.ReplacePlaceholders(self.Keywords) : null) },
			{ "MetaDescription", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.MetaDescription != null ? ctx.ReplacePlaceholders(self.MetaDescription) : null) },
			{ "Tags", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.Tags != null ? ctx.ReplacePlaceholders(self.Tags) : null) },
			{ "IsInSiteMap", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.IsInSiteMap != null ? self.IsInSiteMap.Value ? "1" : "0" : null) },
			{ "IndexOrder", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.IndexOrder != null ? self.IndexOrder.ToString() : null) },
			{ "ExtensionId", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.ExtensionId != null ? self.ExtensionId.ToString() : null) },
			{ "ContentId", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.ContentId != null ? self.ContentId.ToString() : null) },
			{ "TitleFormat_ID", new Func<QPAbstractItem, IQPFormService, string>((self, ctx) => self.TitleFormat_ID != null ? self.TitleFormat_ID.ToString() : null) },
        };

        #endregion
        #region Genarated properties
        public Boolean IsVisibleExact { get { return this.IsVisible == null ? default(Boolean) : this.IsVisible.Value; } }
        public Boolean IsPageExact { get { return this.IsPage == null ? default(Boolean) : this.IsPage.Value; } }
        public Boolean IsInSiteMapExact { get { return this.IsInSiteMap == null ? default(Boolean) : this.IsInSiteMap.Value; } }
        public Int32 IndexOrderExact { get { return this.IndexOrder == null ? default(Int32) : this.IndexOrder.Value; } }
        public Int32 ExtensionIdExact { get { return this.ExtensionId == null ? default(Int32) : this.ExtensionId.Value; } }
        public Int32 ContentIdExact { get { return this.ContentId == null ? default(Int32) : this.ContentId.Value; } }
        public Int32 TitleFormat_IDExact { get { return this.TitleFormat_ID == null ? default(Int32) : this.TitleFormat_ID.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("QPAbstractItem", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class QPDiscriminator: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<QPDiscriminator, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<QPDiscriminator,  IQPFormService, string>>
        {
			{ "Title", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "Name", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.Name != null ? ctx.ReplacePlaceholders(self.Name) : null) },
			{ "PreferredContentId", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.PreferredContentId != null ? self.PreferredContentId.ToString() : null) },
			{ "TypeName", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.TypeName != null ? ctx.ReplacePlaceholders(self.TypeName) : null) },
			{ "CategoryName", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.CategoryName != null ? ctx.ReplacePlaceholders(self.CategoryName) : null) },
			{ "Description", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.Description != null ? ctx.ReplacePlaceholders(self.Description) : null) },
			{ "IconUrl", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.IconUrl != null ? self.IconUrl : null) },
			{ "IsPage", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.IsPage != null ? self.IsPage.Value ? "1" : "0" : null) },
			{ "AllowedZones", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.AllowedZones != null ? ctx.ReplacePlaceholders(self.AllowedZones) : null) },
			{ "FilterPartByUrl", new Func<QPDiscriminator, IQPFormService, string>((self, ctx) => self.FilterPartByUrl != null ? self.FilterPartByUrl.Value ? "1" : "0" : null) },
        };

        #endregion
        #region Genarated properties
        public string IconUrlUrl 
		{ 
			get { return QpDataContext.Current.GetUrl(this.IconUrl, "QPDiscriminator", "IconUrl"); }
		}
        public string IconUrlUploadPath 
		{ 
			get { return QpDataContext.Current.GetUploadPath(this.IconUrl, "QPDiscriminator", "IconUrl"); }
		}
        public Int32 PreferredContentIdExact { get { return this.PreferredContentId == null ? default(Int32) : this.PreferredContentId.Value; } }
        public Boolean IsPageExact { get { return this.IsPage == null ? default(Boolean) : this.IsPage.Value; } }
        public Boolean FilterPartByUrlExact { get { return this.FilterPartByUrl == null ? default(Boolean) : this.FilterPartByUrl.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("QPDiscriminator", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class QPCulture: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<QPCulture, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<QPCulture,  IQPFormService, string>>
        {
			{ "Title", new Func<QPCulture, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "Name", new Func<QPCulture, IQPFormService, string>((self, ctx) => self.Name != null ? ctx.ReplacePlaceholders(self.Name) : null) },
			{ "Icon", new Func<QPCulture, IQPFormService, string>((self, ctx) => self.Icon != null ? self.Icon : null) },
        };

        #endregion
        #region Genarated properties
        public string IconUrl 
		{ 
			get { return QpDataContext.Current.GetUrl(this.Icon, "QPCulture", "Icon"); }
		}
        public string IconUploadPath 
		{ 
			get { return QpDataContext.Current.GetUploadPath(this.Icon, "QPCulture", "Icon"); }
		}
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("QPCulture", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class QPItemDefinitionConstraint: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<QPItemDefinitionConstraint, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<QPItemDefinitionConstraint,  IQPFormService, string>>
        {
			{ "Target_ID", new Func<QPItemDefinitionConstraint, IQPFormService, string>((self, ctx) => self.Target_ID != null ? self.Target_ID.ToString() : null) },
			{ "Source_ID", new Func<QPItemDefinitionConstraint, IQPFormService, string>((self, ctx) => self.Source_ID != null ? self.Source_ID.ToString() : null) },
        };

        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("QPItemDefinitionConstraint", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTest: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTest, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTest,  IQPFormService, string>>
        {
			{ "Title", new Func<AbTest, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "Enabled", new Func<AbTest, IQPFormService, string>((self, ctx) => self.Enabled != null ? self.Enabled.Value ? "1" : "0" : null) },
			{ "Percentage", new Func<AbTest, IQPFormService, string>((self, ctx) => self.Percentage != null ? ctx.ReplacePlaceholders(self.Percentage) : null) },
			{ "StartDate", new Func<AbTest, IQPFormService, string>((self, ctx) => self.StartDate != null ? self.StartDate.ToString() : null) },
			{ "EndDate", new Func<AbTest, IQPFormService, string>((self, ctx) => self.EndDate != null ? self.EndDate.ToString() : null) },
			{ "Comment", new Func<AbTest, IQPFormService, string>((self, ctx) => self.Comment != null ? ctx.ReplacePlaceholders(self.Comment) : null) },
        };

        #endregion
        #region Genarated properties
        public Boolean EnabledExact { get { return this.Enabled == null ? default(Boolean) : this.Enabled.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTest", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTestBaseContainer: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTestBaseContainer, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTestBaseContainer,  IQPFormService, string>>
        {
			{ "ParentTest_ID", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.ParentTest_ID != null ? self.ParentTest_ID.ToString() : null) },
			{ "Description", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.Description != null ? ctx.ReplacePlaceholders(self.Description) : null) },
			{ "AllowedUrlPatterns", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.AllowedUrlPatterns != null ? ctx.ReplacePlaceholders(self.AllowedUrlPatterns) : null) },
			{ "DeniedUrlPatterns", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.DeniedUrlPatterns != null ? ctx.ReplacePlaceholders(self.DeniedUrlPatterns) : null) },
			{ "Domain", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.Domain != null ? ctx.ReplacePlaceholders(self.Domain) : null) },
			{ "Precondition", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.Precondition != null ? ctx.ReplacePlaceholders(self.Precondition) : null) },
			{ "Arguments", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.Arguments != null ? ctx.ReplacePlaceholders(self.Arguments) : null) },
			{ "Type", new Func<AbTestBaseContainer, IQPFormService, string>((self, ctx) => self.Type != null ? self.Type.ToString() : null) },
        };

        #endregion
        #region Genarated properties
        public Int32 TypeExact { get { return this.Type == null ? default(Int32) : this.Type.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTestBaseContainer", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTestScript: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTestScript, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTestScript,  IQPFormService, string>>
        {
			{ "Container_ID", new Func<AbTestScript, IQPFormService, string>((self, ctx) => self.Container_ID != null ? self.Container_ID.ToString() : null) },
			{ "Description", new Func<AbTestScript, IQPFormService, string>((self, ctx) => self.Description != null ? ctx.ReplacePlaceholders(self.Description) : null) },
			{ "VersionNumber", new Func<AbTestScript, IQPFormService, string>((self, ctx) => self.VersionNumber != null ? self.VersionNumber.ToString() : null) },
			{ "ScriptText", new Func<AbTestScript, IQPFormService, string>((self, ctx) => self.ScriptText != null ? ctx.ReplacePlaceholders(self.ScriptText) : null) },
        };

        #endregion
        #region Genarated properties
        public Int32 VersionNumberExact { get { return this.VersionNumber == null ? default(Int32) : this.VersionNumber.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTestScript", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTestScriptContainer: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTestScriptContainer, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTestScriptContainer,  IQPFormService, string>>
        {
			{ "BaseContainer_ID", new Func<AbTestScriptContainer, IQPFormService, string>((self, ctx) => self.BaseContainer_ID != null ? self.BaseContainer_ID.ToString() : null) },
        };

        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTestScriptContainer", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTestClientRedirectContainer: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTestClientRedirectContainer, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTestClientRedirectContainer,  IQPFormService, string>>
        {
			{ "BaseContainer_ID", new Func<AbTestClientRedirectContainer, IQPFormService, string>((self, ctx) => self.BaseContainer_ID != null ? self.BaseContainer_ID.ToString() : null) },
        };

        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTestClientRedirectContainer", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class AbTestClientRedirect: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<AbTestClientRedirect, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<AbTestClientRedirect,  IQPFormService, string>>
        {
			{ "Container_ID", new Func<AbTestClientRedirect, IQPFormService, string>((self, ctx) => self.Container_ID != null ? self.Container_ID.ToString() : null) },
			{ "VersionNumber", new Func<AbTestClientRedirect, IQPFormService, string>((self, ctx) => self.VersionNumber != null ? ctx.ReplacePlaceholders(self.VersionNumber) : null) },
			{ "RedirectUrl", new Func<AbTestClientRedirect, IQPFormService, string>((self, ctx) => self.RedirectUrl != null ? ctx.ReplacePlaceholders(self.RedirectUrl) : null) },
        };

        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("AbTestClientRedirect", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class BlogPost: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<BlogPost, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<BlogPost,  IQPFormService, string>>
        {
			{ "Title", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "Brief", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.Brief != null ? ctx.ReplacePlaceholders(self.Brief) : null) },
			{ "PostDate", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.PostDate != null ? self.PostDate.ToString() : null) },
			{ "Category_ID", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.Category_ID != null ? self.Category_ID.ToString() : null) },
			{ "Text", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.Text != null ? ctx.ReplacePlaceholders(self.Text) : null) },
			{ "Image", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.Image != null ? self.Image : null) },
			{ "YoutubeVideoCode", new Func<BlogPost, IQPFormService, string>((self, ctx) => self.YoutubeVideoCode != null ? ctx.ReplacePlaceholders(self.YoutubeVideoCode) : null) },
        };

        #endregion
        #region Genarated properties
        public string ImageUrl 
		{ 
			get { return QpDataContext.Current.GetUrl(this.Image, "BlogPost", "Image"); }
		}
        public string ImageUploadPath 
		{ 
			get { return QpDataContext.Current.GetUploadPath(this.Image, "BlogPost", "Image"); }
		}
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("BlogPost", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class BlogCategory: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<BlogCategory, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<BlogCategory,  IQPFormService, string>>
        {
			{ "Title", new Func<BlogCategory, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
			{ "SortOrder", new Func<BlogCategory, IQPFormService, string>((self, ctx) => self.SortOrder != null ? self.SortOrder.ToString() : null) },
        };

        #endregion
        #region Genarated properties
        public Int32 SortOrderExact { get { return this.SortOrder == null ? default(Int32) : this.SortOrder.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("BlogCategory", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class BlogTag: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<BlogTag, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<BlogTag,  IQPFormService, string>>
        {
			{ "Title", new Func<BlogTag, IQPFormService, string>((self, ctx) => self.Title != null ? ctx.ReplacePlaceholders(self.Title) : null) },
        };

        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("BlogTag", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
    public partial class FaqItem: IQPArticle
    {
        #region Static members
        protected static readonly Dictionary<string, Func<FaqItem, IQPFormService, string>> _valueExtractors = new Dictionary<string, Func<FaqItem,  IQPFormService, string>>
        {
			{ "Question", new Func<FaqItem, IQPFormService, string>((self, ctx) => self.Question != null ? ctx.ReplacePlaceholders(self.Question) : null) },
			{ "Answer", new Func<FaqItem, IQPFormService, string>((self, ctx) => self.Answer != null ? ctx.ReplacePlaceholders(self.Answer) : null) },
			{ "SortOrder", new Func<FaqItem, IQPFormService, string>((self, ctx) => self.SortOrder != null ? self.SortOrder.ToString() : null) },
        };

        #endregion
        #region Genarated properties
        public Int32 SortOrderExact { get { return this.SortOrder == null ? default(Int32) : this.SortOrder.Value; } }
        #endregion

		
        // для Poco перенести из класса куда-нибудь, так как нарушается концепция доступа к БД
        Hashtable IQPArticle.Pack(IQPFormService context, params string[] propertyNames)
        {
            Hashtable table;

            if (propertyNames == null || propertyNames.Length == 0)
            {
                // todo: filter null values
                table = new Hashtable(_valueExtractors.ToDictionary(x => context.GetFormNameByNetNames("FaqItem", x.Key), y => y.Value(this, context)));
            }
            else
            {
                table = new Hashtable();
                foreach (var prop in propertyNames.Join(_valueExtractors.Keys, x => x, x => x, (x, y) => x))
                {
                    string value = _valueExtractors[prop](this, context);
                    table.Add(prop, value);
                }
            }

            return table;
        }
    }
}
	
	
